[workspace]
members = [
  "marco-morser",
  "test-server"
]
resolver = "1"

[profile.dev]
panic = "unwind"

[profile.release]
strip = true
opt-level = "s"
lto = "fat"
codegen-units = 1
panic = "abort"
